### PR TITLE
Update Socials

### PR DESCRIPTION
**Pull request by lappemic**
Updated the socials with:
- added bluesky
- wrote platform specific texts so we can link the different accounts.
- reordered socials display and
- changed the twitter logo to X

What i am not really sure is the text to share... It just sounds so not authentic:

- I just helped fund open source climate projects through [OPENSUSTAINTECH PLATFORMHANDLE OR LINK]! Join me in supporting sustainable technology! #OpenClimateFund"

Can anyone think of a a better wording for this? @Ly0n, @andrew or @RichardLitt?

### CODE REVIEW

**Comment by Ly0n** [comment]
@lappemic Here an alternative version: I have just nominated an open source climate project via https://openclimate.fund/ or [OPENSUSTAINTECH PLATFORMHANDLE OR LINK] Join us in supporting open climate and environmental technology #OpenClimateFund".

**Comment by lappemic** [comment]
The first part is better!  And the second part as well. Don't you think the 'or' is confusing to people? Should we direct people first to openclimate.fund and then tag opensustain.tech at the end? Something like:

- "I have just nominated an open source climate project via [https://openclimate.fund/](https://openclimate.fund/). Join us in supporting open climate and environmental technology! *An initiative by [https://opensustain.tech](https://opensustain.tech)* #OpenClimateFund"

Actually in these versions there is not even mentioned that someone gets a sponsorship... Should we not include this as well?

**Comment by Ly0n** [comment]
> Don't you think the 'or' is confusing to people? 

The or is just for the link or the handle...We should not use both. I think the link is the better option!

**Comment by lappemic** [comment]
So this would be the social sharing text then (same as above)?
> "I have just nominated an open source climate project via https://openclimate.fund/. Join us in supporting open climate and environmental technology! An initiative by https://opensustain.tech/ #OpenClimateFund"

**Comment by Ly0n** [comment]
Here a small improvement: 

> "I have just nominated an #opensource climate project via [openclimate.fund](https://openclimate.fund/). Join us in supporting open #climate and environmental technology! An initiative by [opensustain.tech](https://opensustain.tech/) #OpenClimateFund"

**Comment by lappemic** [comment]
Updated the text accordingly. -> There is now only one text across all platforms.

**Pull request merged**
