### PR TITLE
Some design optimisations / suggestions

### PR DESCRIPTION
**Pull request by killerog**
Hello,

I came across [this discussion](https://github.com/protontypes/open-sustainable-technology/issues/527), and noticed a few things that seemed a bit off with the design.

So I made some small changes that bothered me the most, but there are others like the massive white spaces or the inconsistent link styles.

Is there a style guide or branding guide somewhere? For now I color picked the blue out of your logo, as that seemed to look better and more consistent, but I'm not totally sure if that's the right tint of blue.

If it's ok, I'll dive a bit deeper in making the design more consistent.

### CODE REVIEW

**Comment by andrew** [comment]
These changes look good, thanks for contributing!

**Comment by killerog** [comment]
I made a few more changes, seems best to do them all in one request?

> Hello,
> 
> I came across [this discussion](https://github.com/protontypes/open-sustainable-technology/issues/527), and noticed a few things that seemed a bit off with the design.
> 
> So I made some small changes that bothered me the most, but there are others like the massive white spaces or the inconsistent link styles.
> 
> Is there a style guide or branding guide somewhere? For now I color picked the blue out of your logo, as that seemed to look better and more consistent, but I'm not totally sure if that's the right tint of blue.
> 
> If it's ok, I'll dive a bit deeper in making the design more consistent.

**Comment by andrew** [comment]
All in one request is good, if you fancy adding screenshots of some of the changes you're making that would be great

**Comment by lappemic** [comment]
Hey @killerog thanks a lot for your PR-request and inputs! The changes look great, hanks a lot! There is no style or branding guide at the moment. Our goal is to keep things as consistent as possible over the projects in
- [opensustain.tech](https://opensustain.tech/)
- [climatetriage.com](https://climatetriage.com/) and
- [openclimate.fund](https://openclimate.fund/)

Obviously these sites serve pretty different purposes and moreover have different frameworks. So there will always be some difference in style and layout. But feel free to make suggestions on how to improve this. Draft PR's are always welcome and are easiest as a discussion starter.

As you probably realized, the site is still a WIP and we are working on finalizing it the next weeks (overview of donation links, proper PR template, wording, additional sections, etc.). So we greatly appreaciate any inputs on this as well.

This said i am going to merge this PR. Feel free to open a new PR for additional optimizations.

**Review by lappemic — APPROVED** [review]

**Comment by killerog** [comment]
Hi, 

Thanks for the feedback.

I don't know if this is the right place for this discussion, but I was wondering why some of the sites have dark theme and only opensustain.tech hasn't?

While you could argue that the design op opensustain.tech is somewhat outdated, the other sites kind of feel like they're on some kind of default theme. 
Without more distinct images, it's kind of hard for them to distinguish but it's also hard to find fitting images for this subject I guess.
Maybe we can do some more with the curves in the logo, if that's ok? I don't know if the shape of the "g" is just in the font or if that's part of these shapes.

I did notice the new design ideas for filtering on opensustain.tech, but I couldn't get all the dependencies to run locally for now so I'll have to look into that after my vacation.

**Comment by lappemic** [comment]
Thank you so much for your inputs @killerog and sorry for the late feedback!

Feel free to always open an issue if you got suggestions for improvements or questions. We do not maintain any open channel outside of this repo at this moment. Whereas there is an open meeting every second tuesday in the month. You can find the meetting link in the calendar of [https://opensustain.tech/contributing/](https://opensustain.tech/contributing/). We would be very happy to welcome you there if you like. :)

This being said, the reason for the different themes is just framework, taste and timespecific. Opensustain.tech is built with mkdocs and was the first project built. Climatetriage as well as openclimate.fund are never projects and based on nextjs.

What problem did you encounter when running opensustain.tech locally? If this persists, as said, please feel free to open an issue on [https://github.com/protontypes/open-sustainable-technology/issues](https://github.com/protontypes/open-sustainable-technology/issues)

**Pull request merged**
